/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Hdpe2PlasticBottleWhereInput } from "./Hdpe2PlasticBottleWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Hdpe2PlasticBottleCountArgs {
  @ApiProperty({
    required: false,
    type: () => Hdpe2PlasticBottleWhereInput,
  })
  @Field(() => Hdpe2PlasticBottleWhereInput, { nullable: true })
  @Type(() => Hdpe2PlasticBottleWhereInput)
  where?: Hdpe2PlasticBottleWhereInput;
}

export { Hdpe2PlasticBottleCountArgs as Hdpe2PlasticBottleCountArgs };
