/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Hdpe2PlasticBottleWhereInput } from "./Hdpe2PlasticBottleWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Hdpe2PlasticBottleListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Hdpe2PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Hdpe2PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Hdpe2PlasticBottleWhereInput, {
    nullable: true,
  })
  every?: Hdpe2PlasticBottleWhereInput;

  @ApiProperty({
    required: false,
    type: () => Hdpe2PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Hdpe2PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Hdpe2PlasticBottleWhereInput, {
    nullable: true,
  })
  some?: Hdpe2PlasticBottleWhereInput;

  @ApiProperty({
    required: false,
    type: () => Hdpe2PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Hdpe2PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Hdpe2PlasticBottleWhereInput, {
    nullable: true,
  })
  none?: Hdpe2PlasticBottleWhereInput;
}
export { Hdpe2PlasticBottleListRelationFilter as Hdpe2PlasticBottleListRelationFilter };
