/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Hdpe2PlasticBottleWhereUniqueInput } from "./Hdpe2PlasticBottleWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Hdpe2PlasticBottleUpdateInput } from "./Hdpe2PlasticBottleUpdateInput";

@ArgsType()
class UpdateHdpe2PlasticBottleArgs {
  @ApiProperty({
    required: true,
    type: () => Hdpe2PlasticBottleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Hdpe2PlasticBottleWhereUniqueInput)
  @Field(() => Hdpe2PlasticBottleWhereUniqueInput, { nullable: false })
  where!: Hdpe2PlasticBottleWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Hdpe2PlasticBottleUpdateInput,
  })
  @ValidateNested()
  @Type(() => Hdpe2PlasticBottleUpdateInput)
  @Field(() => Hdpe2PlasticBottleUpdateInput, { nullable: false })
  data!: Hdpe2PlasticBottleUpdateInput;
}

export { UpdateHdpe2PlasticBottleArgs as UpdateHdpe2PlasticBottleArgs };
