/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AluminiumCan } from "./AluminiumCan";
import { AluminiumCanCountArgs } from "./AluminiumCanCountArgs";
import { AluminiumCanFindManyArgs } from "./AluminiumCanFindManyArgs";
import { AluminiumCanFindUniqueArgs } from "./AluminiumCanFindUniqueArgs";
import { DeleteAluminiumCanArgs } from "./DeleteAluminiumCanArgs";
import { AluminiumCanService } from "../aluminiumCan.service";
@graphql.Resolver(() => AluminiumCan)
export class AluminiumCanResolverBase {
  constructor(protected readonly service: AluminiumCanService) {}

  async _aluminiumCansMeta(
    @graphql.Args() args: AluminiumCanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AluminiumCan])
  async aluminiumCans(
    @graphql.Args() args: AluminiumCanFindManyArgs
  ): Promise<AluminiumCan[]> {
    return this.service.aluminiumCans(args);
  }

  @graphql.Query(() => AluminiumCan, { nullable: true })
  async aluminiumCan(
    @graphql.Args() args: AluminiumCanFindUniqueArgs
  ): Promise<AluminiumCan | null> {
    const result = await this.service.aluminiumCan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AluminiumCan)
  async deleteAluminiumCan(
    @graphql.Args() args: DeleteAluminiumCanArgs
  ): Promise<AluminiumCan | null> {
    try {
      return await this.service.deleteAluminiumCan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
