/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Pet1PlasticBottleWhereInput } from "./Pet1PlasticBottleWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Pet1PlasticBottleListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Pet1PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Pet1PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Pet1PlasticBottleWhereInput, {
    nullable: true,
  })
  every?: Pet1PlasticBottleWhereInput;

  @ApiProperty({
    required: false,
    type: () => Pet1PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Pet1PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Pet1PlasticBottleWhereInput, {
    nullable: true,
  })
  some?: Pet1PlasticBottleWhereInput;

  @ApiProperty({
    required: false,
    type: () => Pet1PlasticBottleWhereInput,
  })
  @ValidateNested()
  @Type(() => Pet1PlasticBottleWhereInput)
  @IsOptional()
  @Field(() => Pet1PlasticBottleWhereInput, {
    nullable: true,
  })
  none?: Pet1PlasticBottleWhereInput;
}
export { Pet1PlasticBottleListRelationFilter as Pet1PlasticBottleListRelationFilter };
