/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Pet1PlasticBottleWhereInput } from "./Pet1PlasticBottleWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Pet1PlasticBottleOrderByInput } from "./Pet1PlasticBottleOrderByInput";

@ArgsType()
class Pet1PlasticBottleFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Pet1PlasticBottleWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Pet1PlasticBottleWhereInput, { nullable: true })
  @Type(() => Pet1PlasticBottleWhereInput)
  where?: Pet1PlasticBottleWhereInput;

  @ApiProperty({
    required: false,
    type: [Pet1PlasticBottleOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Pet1PlasticBottleOrderByInput], { nullable: true })
  @Type(() => Pet1PlasticBottleOrderByInput)
  orderBy?: Array<Pet1PlasticBottleOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Pet1PlasticBottleFindManyArgs as Pet1PlasticBottleFindManyArgs };
