/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Pet1PlasticBottleWhereUniqueInput } from "./Pet1PlasticBottleWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Pet1PlasticBottleUpdateInput } from "./Pet1PlasticBottleUpdateInput";

@ArgsType()
class UpdatePet1PlasticBottleArgs {
  @ApiProperty({
    required: true,
    type: () => Pet1PlasticBottleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Pet1PlasticBottleWhereUniqueInput)
  @Field(() => Pet1PlasticBottleWhereUniqueInput, { nullable: false })
  where!: Pet1PlasticBottleWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Pet1PlasticBottleUpdateInput,
  })
  @ValidateNested()
  @Type(() => Pet1PlasticBottleUpdateInput)
  @Field(() => Pet1PlasticBottleUpdateInput, { nullable: false })
  data!: Pet1PlasticBottleUpdateInput;
}

export { UpdatePet1PlasticBottleArgs as UpdatePet1PlasticBottleArgs };
